-- ============================================================================
-- Fishery quota ledger schema (FICTIONAL DEMO ONLY)
-- All weight columns use NUMERIC(14,3) and are mapped to BigDecimal in Java.
-- ============================================================================

CREATE TABLE IF NOT EXISTS species (
    code        TEXT PRIMARY KEY,
    name        TEXT NOT NULL,
    fictional   BOOLEAN NOT NULL DEFAULT TRUE,
    note        TEXT
);

CREATE TABLE IF NOT EXISTS sea_area (
    code        TEXT PRIMARY KEY,
    name        TEXT NOT NULL,
    note        TEXT
);

CREATE TABLE IF NOT EXISTS season (
    code        TEXT PRIMARY KEY,
    name        TEXT NOT NULL,
    starts_on   DATE NOT NULL,
    ends_on     DATE NOT NULL,
    CHECK (ends_on >= starts_on)
);

-- Permission rule: species may only be caught in this area during this season.
-- Completely fictional licensing matrix; does NOT represent a real permit.
CREATE TABLE IF NOT EXISTS species_permit (
    species_code    TEXT NOT NULL REFERENCES species(code),
    area_code       TEXT NOT NULL REFERENCES sea_area(code),
    season_code     TEXT NOT NULL REFERENCES season(code),
    PRIMARY KEY (species_code, area_code, season_code)
);

CREATE TABLE IF NOT EXISTS vessel (
    code        TEXT PRIMARY KEY,
    name        TEXT NOT NULL,
    home_port   TEXT NOT NULL
);

-- One quota balance per vessel + species + sea area + season.
-- The area dimension enforces "quota for a non-matching area cannot be used":
-- balances are separate ledger accounts, never pooled across areas.
CREATE TABLE IF NOT EXISTS quota_account (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vessel_code     TEXT NOT NULL REFERENCES vessel(code),
    species_code    TEXT NOT NULL REFERENCES species(code),
    area_code       TEXT NOT NULL REFERENCES sea_area(code),
    season_code     TEXT NOT NULL REFERENCES season(code),
    issued_qty      NUMERIC(14,3) NOT NULL DEFAULT 0,
    reserved_qty    NUMERIC(14,3) NOT NULL DEFAULT 0,
    landed_qty      NUMERIC(14,3) NOT NULL DEFAULT 0,
    transferred_in_qty  NUMERIC(14,3) NOT NULL DEFAULT 0,
    transferred_out_qty NUMERIC(14,3) NOT NULL DEFAULT 0,
    version         BIGINT NOT NULL DEFAULT 0,
    CHECK (issued_qty >= 0 AND reserved_qty >= 0 AND landed_qty >= 0),
    CHECK (transferred_in_qty >= 0 AND transferred_out_qty >= 0),
    UNIQUE (vessel_code, species_code, area_code, season_code)
);

-- Append-only, immutable ledger. UPDATE / DELETE are blocked by a trigger.
CREATE TABLE IF NOT EXISTS quota_ledger_entry (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id      BIGINT NOT NULL REFERENCES quota_account(id),
    event_type      TEXT NOT NULL CHECK (event_type IN
                        ('ISSUE','RESERVE','LANDING','SETTLE_RESERVE','TRANSFER_OUT','TRANSFER_IN')),
    amount          NUMERIC(14,3) NOT NULL, -- signed: credit positive, debit negative
    balance_after   NUMERIC(14,3) NOT NULL,  -- issued - reserved - landed + in - out (available)
    event_date      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ref_type        TEXT,
    ref_id          BIGINT,
    memo            TEXT
);

CREATE TABLE IF NOT EXISTS voyage (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voyage_no       TEXT NOT NULL UNIQUE,
    vessel_code     TEXT NOT NULL REFERENCES vessel(code),
    area_code       TEXT NOT NULL REFERENCES sea_area(code),
    season_code     TEXT NOT NULL REFERENCES season(code),
    departs_on      DATE NOT NULL,
    returns_on      DATE,
    status          TEXT NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','CLOSED')),
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- One estimated-use line per species on a voyage declaration.
CREATE TABLE IF NOT EXISTS voyage_declaration (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voyage_id       BIGINT NOT NULL REFERENCES voyage(id),
    species_code    TEXT NOT NULL REFERENCES species(code),
    estimated_qty   NUMERIC(14,3) NOT NULL CHECK (estimated_qty > 0),
    landed_qty      NUMERIC(14,3) NOT NULL DEFAULT 0,
    reserved_qty    NUMERIC(14,3) NOT NULL DEFAULT 0,
    settled         BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (voyage_id, species_code)
);

CREATE TABLE IF NOT EXISTS landing_voucher (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_no          TEXT NOT NULL UNIQUE, -- idempotency key: re-posting never double-deducts
    voyage_id           BIGINT NOT NULL REFERENCES voyage(id),
    species_code        TEXT NOT NULL REFERENCES species(code),
    area_code           TEXT NOT NULL REFERENCES sea_area(code),
    season_code         TEXT NOT NULL REFERENCES season(code),
    landed_qty          NUMERIC(14,3) NOT NULL CHECK (landed_qty > 0),
    recorded_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- A transfer moves quota from one account to another as ONE logical event.
-- Both legs share transfer_id, so balances are never edited "bare".
CREATE TABLE IF NOT EXISTS quota_transfer (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_no         TEXT NOT NULL UNIQUE,
    species_code        TEXT NOT NULL REFERENCES species(code),
    area_code           TEXT NOT NULL REFERENCES sea_area(code),
    season_code         TEXT NOT NULL REFERENCES season(code),
    qty                 NUMERIC(14,3) NOT NULL CHECK (qty > 0),
    from_account_id     BIGINT NOT NULL REFERENCES quota_account(id),
    to_account_id       BIGINT NOT NULL REFERENCES quota_account(id),
    effective_from      DATE NOT NULL,
    effective_to        DATE NOT NULL,
    status              TEXT NOT NULL DEFAULT 'EFFECTIVE'
                            CHECK (status IN ('PLANNED','EFFECTIVE','EXPIRED','REJECTED')),
    memo                TEXT,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (from_account_id <> to_account_id),
    CHECK (effective_to >= effective_from)
);

-- Prevent ledger tampering: quota_ledger_entry is append-only.
CREATE OR REPLACE FUNCTION quota_ledger_block_change() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'quota_ledger_entry is append-only; % is not allowed', TG_OP;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_quota_ledger_no_update ON quota_ledger_entry;
CREATE TRIGGER trg_quota_ledger_no_update BEFORE UPDATE ON quota_ledger_entry
    FOR EACH ROW EXECUTE FUNCTION quota_ledger_block_change();

DROP TRIGGER IF EXISTS trg_quota_ledger_no_delete ON quota_ledger_entry;
CREATE TRIGGER trg_quota_ledger_no_delete BEFORE DELETE ON quota_ledger_entry
    FOR EACH ROW EXECUTE FUNCTION quota_ledger_block_change();

-- Invariant guard: available balance of an account may never go negative.
CREATE OR REPLACE FUNCTION quota_account_non_negative() RETURNS trigger AS $$
BEGIN
    IF NEW.issued_qty + NEW.transferred_in_qty
       - NEW.transferred_out_qty - NEW.reserved_qty - NEW.landed_qty < -0.0001 THEN
        RAISE EXCEPTION 'account %s available balance would go negative', NEW.id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_quota_account_non_negative ON quota_account;
CREATE TRIGGER trg_quota_account_non_negative BEFORE UPDATE OR INSERT ON quota_account
    FOR EACH ROW EXECUTE FUNCTION quota_account_non_negative();
